/* BADASS APOCALYPSE - hand-drawn pixel art icons, rasterised at runtime.
   Each icon is a 16x16 character grid plus a per-icon palette. Rows shorter
   than 16 are padded, so a miscounted row degrades instead of exploding. */
(function () {
  'use strict';

  const SIZE = 16;
  const K = '#140c11';        // shared outline
  const W = '#ffffff';

  const ICONS = {
    /* ---------------------------------------------------------- weapons */
    spikes: {
      p: { k: K, s: '#e8eef7', S: '#9fb0c6', d: '#5c6a7d', m: '#8a2b22', M: '#c4382c' },
      g: [
        '       kk       ',
        '      ksSk      ',
        '  kk  ksSk  kk  ',
        ' ksSk ksSk ksSk ',
        ' ksSk ksSk ksSk ',
        'ksSSk ksSk ksSSk',
        'ksSSk ksSk ksSSk',
        'ksSSkkksSkkksSSk',
        'kkkkkkkkkkkkkkkk',
        'kMMMMMMMMMMMMMMk',
        'kMmmMmmMmmMmmMMk',
        'kMMMMMMMMMMMMMMk',
        'kkkkkkkkkkkkkkkk',
        '  kdk      kdk  ',
        '  kdk      kdk  ',
        '  kkk      kkk  ',
      ],
    },
    rocket: {
      p: { k: K, r: '#e8492f', R: '#ff8a5c', w: W, g: '#b9c6d8', f: '#ffd23a', o: '#ff8a1e' },
      g: [
        '       kk       ',
        '      kwwk      ',
        '      kwwk      ',
        '     krRRk      ',
        '     krRRk      ',
        '     krRRk      ',
        '    kkrRRkk     ',
        '   kggkRRkggk   ',
        '  kgggkRRkgggk  ',
        '  kggkkRRkkggk  ',
        '  kkk krrk kkk  ',
        '      kkkk      ',
        '      kffk      ',
        '     kfoofk     ',
        '     kfoofk     ',
        '      koak      ',
      ],
    },
    saw: {
      p: { k: K, s: '#dbe4f0', S: '#95a5bb', d: '#4c586a', r: '#b8202a' },
      g: [
        '   k        k   ',
        '  kSk  kk  kSk  ',
        '  kSkkksskkkSk  ',
        ' kkSssssssssSkk ',
        ' kssssSSSSssssk ',
        'kkssSSddddSSsskk',
        'ksssSdd  ddSsssk',
        'ksssSd    dSsssk',
        'ksssSd    dSsssk',
        'ksssSdd  ddSsssk',
        'kkssSSddddSSsskk',
        ' kssssSSSSssssk ',
        ' kkSssssssssSkk ',
        '  kSkkksskkkSk  ',
        '  kSk  kk  kSk  ',
        '   k   rr   k   ',
      ],
    },
    flame: {
      p: { k: K, y: '#ffe45c', o: '#ff9c1e', r: '#ef4423', d: '#8f1a10' },
      g: [
        '       kk       ',
        '      krrk      ',
        '     krrrrk     ',
        '  k  krorrk  k  ',
        ' krk krorrk krk ',
        ' krrkkroorkkrrk ',
        'krorrkroyorkrrok',
        'kroorkryyyrkroor',
        'krooorryyyrrooor',
        'kroooooyyyooooor',
        'kdooooyyyyyoooodk',
        ' kdoooyywyyooodk',
        ' kkdooyywyyoodkk',
        '  kkdoooyoooddk ',
        '    kkdoooodkk  ',
        '      kkddkk    ',
      ],
    },
    minigun: {
      p: { k: K, g: '#8d99ab', G: '#c3ceda', d: '#464f5d', y: '#ffd23a', o: '#ff8a1e' },
      g: [
        '                ',
        '            kkkk',
        '        kkkkgGGk',
        '     kkkgggggGGk',
        'y   kdGGGGGGGGGk',
        'yo kkdGGkkkkkkkk',
        'yookdGGkkkkkkkk ',
        ' okdGGGGGGGGGk  ',
        '  kdGGkkkkkkk   ',
        '  kdGGk kkkk    ',
        '  kkdGGGGGGk    ',
        '   kkddGGddk    ',
        '     kkdddk     ',
        '      kddk      ',
        '     kkddkk     ',
        '     kkkkkk     ',
      ],
    },
    tesla: {
      p: { k: K, b: '#63d3ff', B: '#bff0ff', w: W, d: '#1b6f9c' },
      g: [
        '        kk      ',
        '       kBBk     ',
        '      kBBbk     ',
        '     kBBbdk     ',
        '    kBBbbdk     ',
        '   kBBbbddk     ',
        '  kBBbbdddk     ',
        ' kBBbbkkkkkkkk  ',
        ' kbbkkkkbbBBBk  ',
        ' kkk   kbbBBk   ',
        '      kbbBBk    ',
        '     kbbBBk     ',
        '    kbbBBk      ',
        '   kbbBBk       ',
        '   kbBBk        ',
        '   kkkk         ',
      ],
    },
    mine: {
      p: { k: K, d: '#2b2f38', g: '#525a68', w: W, o: '#ff8a1e', y: '#ffe45c' },
      g: [
        '            kyk ',
        '           kyok ',
        '          kokk  ',
        '     kkk kok    ',
        '   kkgggkkk     ',
        '  kgggggggk     ',
        ' kggwwggggkk    ',
        ' kgwwgggggdk    ',
        'kggwggggggddk   ',
        'kgggggggggddk   ',
        'kggggggggdddk   ',
        'kgggggggdddkk   ',
        ' kggggddddk     ',
        ' kkgdddddkk     ',
        '  kkddddkk      ',
        '    kkkk        ',
      ],
    },
    slam: {
      p: { k: K, p: '#c68bff', P: '#e9d3ff', b: '#7a4bd0', w: W },
      g: [
        '   k   kk   k   ',
        '   kp  kPk  pk  ',
        '    kp kPk pk   ',
        ' k   kpkPkpk   k',
        ' kp   kPPPk   pk',
        '  kpp kPwPk ppk ',
        '   kppkPwPkppk  ',
        'kkkkkppkwkppkkkk',
        'kPPPPPwwwwwPPPPk',
        'kkkkkppkwkppkkkk',
        '   kppkPwPkppk  ',
        '  kpp kPwPk ppk ',
        ' kp   kPPPk   pk',
        ' k   kpkPkpk   k',
        '    kp kPk pk   ',
        '   k   kPk   k  ',
      ],
    },

    /* --------------------------------------------------------- passives */
    engine: {
      p: { k: K, r: '#e8382c', R: '#ff7a5c', d: '#7a1a12', g: '#98a4b5', y: '#ffd23a' },
      g: [
        '                ',
        '   kk      kk   ',
        '  kggk    kggk  ',
        '  kggkkkkkggk   ',
        ' kkRRRRRRRRRkk  ',
        'kRRRRRRRRRRRRRk ',
        'kRRkyykRRkyykRk ',
        'kRRkyykRRkyykRk ',
        'krrrrrrrrrrrrrk ',
        'krrddrrrrddrrrk ',
        'kkrrrrrrrrrrrkk ',
        ' kkdddddddddkk  ',
        '  kkgkkkkkgkk   ',
        '   kggk  kggk   ',
        '   kkkk  kkkk   ',
        '                ',
      ],
    },
    turbo: {
      p: { k: K, b: '#4dd2ff', B: '#c2f0ff', d: '#1c6f96', g: '#9aa7b8' },
      g: [
        '     kkkkkk     ',
        '   kkBBBBBBkk   ',
        '  kBBbbbbbbBBk  ',
        ' kBBbbddddbbBBk ',
        ' kBbbdd  ddbbBk ',
        'kBBbd  kk  dbBBk',
        'kBbbd kBBk dbbBk',
        'kBbd  kBBk  dbBk',
        'kBbd  kBBk  dbBk',
        'kBbbd kBBk dbbBk',
        'kBBbd  kk  dbBBk',
        ' kBbbdd  ddbbBk ',
        ' kBBbbddddbbBBk ',
        '  kBBbbbbbbBBk  ',
        '   kkBBBBBBkk   ',
        '     kkkkkk     ',
      ],
    },
    grip: {
      p: { k: K, d: '#22262e', g: '#3b4250', s: '#c8d2e0', S: '#8d99ab' },
      g: [
        '    kkkkkkkk    ',
        '  kkddddddddkk  ',
        ' kdgdgdgdgdgddk ',
        'kddddddddddddddk',
        'kdgdkkkkkkkkgddk',
        'kddkkSSSSSSkkddk',
        'kdgkSSsssSSSkgdk',
        'kddkSsskkssSkddk',
        'kddkSsskkssSkddk',
        'kdgkSSsssSSSkgdk',
        'kddkkSSSSSSkkddk',
        'kdgdkkkkkkkkgddk',
        'kddddddddddddddk',
        ' kdgdgdgdgdgddk ',
        '  kkddddddddkk  ',
        '    kkkkkkkk    ',
      ],
    },
    armor: {
      p: { k: K, g: '#7fd18f', G: '#c8f0d0', d: '#2f7a45', s: '#dbe4f0' },
      g: [
        '    kkkkkkkk    ',
        '  kkGGGGGGGGkk  ',
        ' kGGGggggggGGGk ',
        'kGGgggggggggggGk',
        'kGgggggddgggggGk',
        'kGggggdddgggggGk',
        'kgggddddddddgggk',
        'kgggddddddddgggk',
        'kgggggdddgggggkk',
        'kdggggdddgggggk ',
        'kddgggddgggggdk ',
        ' kddggggggggdk  ',
        '  kddggggggdk   ',
        '   kkddggddk    ',
        '     kkddkk     ',
        '       kk       ',
      ],
    },
    magnet: {
      p: { k: K, r: '#ff5c7a', R: '#ffb0c0', s: '#dbe4f0', S: '#95a5bb', b: '#63d3ff' },
      g: [
        '     kkkkkk     ',
        '   kkRRRRRRkk   ',
        '  kRRrrrrrrRRk  ',
        ' kRRrrkkkkrrRRk ',
        ' kRrrk    krrRk ',
        'kRRrk      krRRk',
        'kRrrk      krrRk',
        'kRrrk      krrRk',
        'kRrrk      krrRk',
        'kRrrk      krrRk',
        'kSSSk      kSSSk',
        'kssSk      kSssk',
        'kssSk      kSssk',
        'kkkkk      kkkkk',
        '  b          b  ',
        ' b b        b b ',
      ],
    },
    overdrive: {
      p: { k: K, w: W, s: '#d8dee8', d: '#8a93a3', r: '#ff3b30' },
      g: [
        '    kkkkkkkk    ',
        '  kkwwwwwwwwkk  ',
        ' kwwwwwwwwwwwwk ',
        'kwwwwwwwwwwwwwwk',
        'kwwkkkwwwkkkwwwk',
        'kwkrrrkwkrrrkwwk',
        'kwkrrrkwkrrrkwwk',
        'kwwkkkwwwkkkwwsk',
        'kwwwwwkkkwwwwwsk',
        'kswwwwwwwwwwwssk',
        ' kswwkwkwkwwssk ',
        '  kkswwwwwwskk  ',
        '   kkskwkwkkk   ',
        '    kkdkdkdk    ',
        '      kkkk      ',
        '                ',
      ],
    },
    coolant: {
      p: { k: K, b: '#9fe8ff', B: '#e6faff', d: '#2f8fb8', w: W },
      g: [
        '       kk       ',
        '   k  kBBk  k   ',
        '   kb kBBk bk   ',
        '    kbkBBkbk    ',
        '  kkkbbBBbbkkk  ',
        '   kkbbBBbbkk   ',
        '  kbbbbBBbbbbk  ',
        'kkbbbbbwwbbbbbkk',
        'kBBBBBwwwwBBBBBk',
        'kkbbbbbwwbbbbbkk',
        '  kbbbbBBbbbbk  ',
        '   kkbbBBbbkk   ',
        '  kkkbbBBbbkkk  ',
        '    kbkBBkbk    ',
        '   kb kBBk bk   ',
        '   k  kkkk  k   ',
      ],
    },
    lucky: {
      p: { k: K, w: W, s: '#cfd6e2', d: '#7b8494', r: '#d2a6ff', b: '#2a2f38' },
      g: [
        '                ',
        '    kkkkkkkk    ',
        '   kwwwwwwwwk   ',
        '  kwwbwwwwbwwk  ',
        ' kwwwbwwwwbwwwk ',
        ' kwwwwwbbwwwwwk ',
        ' kwwwwwbbwwwwwk ',
        ' kwwbwwwwwwbwwk ',
        ' kwwbwwwwwwbwsk ',
        ' kwwwwwwwwwwssk ',
        ' kswwwwwwwwsssk ',
        '  kssswwwsssdk  ',
        '   kkssssssdk   ',
        '    kkddddkk    ',
        '  r   kkkk   r  ',
        ' r r        r r ',
      ],
    },
    hydraulics: {
      p: { k: K, g: '#9aa7b8', G: '#dbe4f0', d: '#4a5462', t: '#7fffd4' },
      g: [
        '   kkkkkkkkkk   ',
        '   kGGGGGGGGk   ',
        '   kkdddddddk   ',
        '     kgGGgk     ',
        '   kkkgGGgkkk   ',
        '  kGGgggggggGk  ',
        '  kkkkgGGgkkkk  ',
        '   kkkgGGgkkk   ',
        '  kGGgggggggGk  ',
        '  kkkkgGGgkkkk  ',
        '   kkkgGGgkkk   ',
        '  kGGgggggggGk  ',
        '   kkkgGGgkkk   ',
        '   kkdddddddk   ',
        '   kGGGGGGGGk   ',
        '   kkkkkkkkkk   ',
      ],
    },
    ramplate: {
      p: { k: K, o: '#e0a06a', O: '#ffd0a0', d: '#8a5a30', s: '#c8d2e0' },
      g: [
        '                ',
        '  kkkkkkkkkkkk  ',
        ' kOOOOOOOOOOOOk ',
        ' kOooooooooooOk ',
        ' kOodoooooodoOk ',
        ' kOoooooooooOk  ',
        ' kkOooooooooOk  ',
        '  kkOoooooooOk  ',
        '   kkOooooooOk  ',
        '    kkOoooooOk  ',
        '     kkOooooOk  ',
        '      kkOoooOk  ',
        '   kss kkOooOk  ',
        '   kss  kkOoOk  ',
        '   kss   kkOkk  ',
        '   kkk    kkk   ',
      ],
    },
    repair: {
      p: { k: K, s: '#d8dee8', S: '#98a4b5', g: '#7dffa0', d: '#4a5462' },
      g: [
        '        kkkk    ',
        '       kssskk   ',
        '      kssk kk   ',
        '      ksk       ',
        '      kssk  kk  ',
        '   kk  ksskssk  ',
        '  kSSk  ksssk   ',
        '  kSSSk  kkk    ',
        '   kSSSk        ',
        '    kSSSk       ',
        '     kSSSk      ',
        '      kSSSk     ',
        '       kSSSk    ',
        '  g     kSSk    ',
        ' g g     kkk    ',
        '  g             ',
      ],
    },
    gas: {
      p: { k: K, r: '#e8492f', R: '#ff8a5c', d: '#8f1a10', y: '#ffd23a', s: '#c8d2e0' },
      g: [
        '     kkkk       ',
        '    ksskk       ',
        '  kkkkkkkkkkk   ',
        ' kRRRRRRRRRRRk  ',
        'kkRRRRRRRRRRRkk ',
        'krRRRRRRRRRRRrk ',
        'krRRkyyyykRRRrkk',
        'krRRkyyyykRRRrrk',
        'krRRRkyykRRRRrrk',
        'krRRRRkkRRRRRrrk',
        'krrRRRRRRRRRrrkk',
        'kdrrRRRRRRRrrdk ',
        'kddrrrrrrrrrddk ',
        'kkddddddddddkkk ',
        ' kkkkkkkkkkkk   ',
        '                ',
      ],
    },

    /* ------------------------------------------------------- resources */
    res_scrap: {
      p: { k: K, y: '#ffd23a', o: '#c98f14', d: '#7a5606', g: '#9aa7b8' },
      g: [
        '                ',
        '      kkkk      ',
        '    kkyyyykk    ',
        '   kyyoyyyoyk   ',
        '  kyyoyyyyyoyk  ',
        ' kkyyyyoyyyyykk ',
        ' kyoyyyyyyoyyyk ',
        ' kyyyyoyyyyyoyk ',
        ' kdyyyyyyoyyydk ',
        ' kddyoyyyyyddgk ',
        '  kddyyyyoyddk  ',
        '   kdddyyyddk   ',
        '    kkdddddk    ',
        '  kgk kkkkk kgk ',
        ' kggk       kgk ',
        '  kk         kk ',
      ],
    },
    res_steel: {
      p: { k: K, s: '#cdd8e6', S: '#8d9cb0', d: '#4d5765' },
      g: [
        '                ',
        '      kkkkkkkk  ',
        '    kkssssssskk ',
        '   ksssssssssSk ',
        '  kkkkkkkkkkkSk ',
        ' kkssssssssskSk ',
        ' ksssssssssSkSk ',
        ' kSkkkkkkkkkkkk ',
        'kkssssssssskSk  ',
        'ksssssssssSkSk  ',
        'kSSSSSSSSSSkk   ',
        'kddddddddddk    ',
        ' kkkkkkkkkk     ',
        '                ',
        '                ',
        '                ',
      ],
    },
    res_food: {
      p: { k: K, g: '#8dff3a', G: '#d4ffb0', d: '#2f7a1c', r: '#ff5c5c', b: '#6b4a22' },
      g: [
        '        kk      ',
        '       kbk      ',
        '      kbgk      ',
        '    kkgGgkk     ',
        '   kgGggggGk    ',
        '  kgGgggggggk   ',
        ' kgGggggggdggk  ',
        ' kggggggggdggk  ',
        'kgGgggggggdgggk ',
        'kgggggggggdgggk ',
        'kdggggggggdggdk ',
        'kddgggggggggddk ',
        ' kddgggggggddk  ',
        '  kdddgggddddk  ',
        '   kkddddddkk   ',
        '     kkkkkk     ',
      ],
    },
    res_meds: {
      p: { k: K, w: '#f2f5fa', s: '#c3ccd9', r: '#ff4d5e', d: '#8a1220' },
      g: [
        '                ',
        '     kkkkkk     ',
        '   kkwwwwwwkk   ',
        '  kwwwwwwwwwwk  ',
        ' kkkkkkkkkkkkkk ',
        ' kwwwwwwwwwwwwk ',
        ' kwwwwwrrwwwwwk ',
        ' kwwwwwrrwwwwwk ',
        ' kwwwrrrrrrwwwk ',
        ' kwwwrrrrrrwwwk ',
        ' kwwwwwrrwwwwwk ',
        ' kswwwwrrwwwwsk ',
        ' kssswwwwwwsssk ',
        ' kdssssssssssdk ',
        '  kkkkkkkkkkkk  ',
        '                ',
      ],
    },
    res_people: {
      p: { k: K, s: '#e8c9a0', b: '#4d9de0', d: '#26557a', g: '#7fd4ff' },
      g: [
        '      kkkk      ',
        '     kssssk     ',
        '    ksssssskk   ',
        '    ksskkssbk   ',
        '    kssssssbk   ',
        '     kssssbk    ',
        '   kkkksskkkk   ',
        '  kbbbbbbbbbbk  ',
        ' kbbbbggbbbbbbk ',
        ' kbbbbggbbbbbbk ',
        ' ksbbggggggbbsk ',
        ' ksbbbbggbbbbsk ',
        ' kdbbbbbbbbbdk  ',
        '  kbbbk kbbbk   ',
        '  kddk   kddk   ',
        '  kkk     kkk   ',
      ],
    },

    /* ------------------------------------------------------- buildings */
    bld_hq: {
      p: { k: K, s: '#8d9cb0', S: '#cdd8e6', d: '#4d5765', y: '#ffd23a', r: '#ff4d4d' },
      g: [
        '       kk       ',
        '      kryk      ',
        '      krrk      ',
        '      kkkk      ',
        '     kSSSSk     ',
        '    kSSSSSSk    ',
        '   kSSyySSSSk   ',
        '  kSSSyySSSSSk  ',
        ' kSSSSSSSSSSSSk ',
        'kssssssssssssssk',
        'ksskkssskkssskkk',
        'ksskkssskkssskdk',
        'kssssssssssssssk',
        'ksskkkssskkksssk',
        'kddddddddddddddk',
        ' kkkkkkkkkkkkkk ',
      ],
    },
    bld_house: {
      p: { k: K, w: '#b9744a', W: '#e0a06a', d: '#5c3418', b: '#4d9de0', s: '#8d9cb0' },
      g: [
        '                ',
        '       kk       ',
        '      kssk      ',
        '     kkWWkk     ',
        '   kkWWWWWWkk   ',
        '  kWWWWWWWWWWk  ',
        ' kWWWWWWWWWWWWk ',
        'kkkkkkkkkkkkkkkk',
        'kwwwwwwwwwwwwwwk',
        'kwkbbkwwwkbbkwwk',
        'kwkbbkwwwkbbkwwk',
        'kwwwwwwwwwwwwwwk',
        'kwwwwkdddkwwwwwk',
        'kwwwwkdddkwwwwwk',
        'kddddkdddkddddkk',
        ' kkkkkkkkkkkkk  ',
      ],
    },
    bld_farm: {
      p: { k: K, g: '#8dff3a', d: '#2f7a1c', b: '#6b4a22', w: '#9fe8ff' },
      g: [
        '  k          k  ',
        '  kw    k   wk  ',
        '   k   kwk  k   ',
        '                ',
        '  kgk  kgk  kgk ',
        ' kgggkkgggkkgggk',
        ' kgdgkkgdgkkgdgk',
        'kkgggkkgggkkgggk',
        'kbkgkkkkgkkkkgkk',
        'kbbkkbbkkbbkkbbk',
        'kbbbbbbbbbbbbbbk',
        'kdbbdbbdbbdbbdbk',
        'kbbbbbbbbbbbbbbk',
        'kddddddddddddddk',
        ' kkkkkkkkkkkkkk ',
        '                ',
      ],
    },
    bld_workshop: {
      p: { k: K, s: '#8d9cb0', S: '#cdd8e6', d: '#4d5765', y: '#ffd23a', o: '#ff8a3d' },
      g: [
        '                ',
        ' kk         kk  ',
        ' kdk       kdk  ',
        ' kdkkkkkkkkkdk  ',
        'kkSkkSkkSkkSkkk ',
        'kSSSSSSSSSSSSSk ',
        'ksssssssssssssk ',
        'kssyyyksssyyysk ',
        'kssyyyksssyyysk ',
        'kssssskssssssdk ',
        'ksooosksooooosk ',
        'ksooosksooooosk ',
        'ksssssksssssssk ',
        'kdddddkdddddddk ',
        ' kkkkkkkkkkkkk  ',
        '                ',
      ],
    },
    bld_foundry: {
      p: { k: K, s: '#6f7b8c', d: '#3a424e', o: '#ff8a1e', y: '#ffe45c', r: '#ef4423' },
      g: [
        '   kk           ',
        '  koyk    kk    ',
        '  koyk   koyk   ',
        '  ksk    ksk    ',
        ' kkskkkkkkskkk  ',
        ' ksssssssssssk  ',
        ' kssssssssssdk  ',
        'kkssrrrrrssssdk ',
        'ksssroooorsssdk ',
        'kssroyyyyorssdk ',
        'kssroyyyyorssdk ',
        'ksssroooorsssdk ',
        'kssssrrrrssssdk ',
        'kdddddddddddddk ',
        ' kkkkkkkkkkkkk  ',
        '                ',
      ],
    },
    bld_refinery: {
      p: { k: K, s: '#8d9cb0', d: '#4a5462', o: '#ff9c1e', y: '#ffd23a' },
      g: [
        '   kk      kk   ',
        '  kssk    kssk  ',
        '  ksskkkkkssk   ',
        '  ksssssssssk   ',
        ' kkssssssssskk  ',
        ' kssoooooooosk  ',
        ' kssoyyyyyyosk  ',
        ' kssoyyyyyyosk  ',
        ' kssoyyyyyyosk  ',
        ' kssoyyyyyyosk  ',
        ' kssoooooooosk  ',
        ' kdsssssssssdk  ',
        ' kdkkkkkkkkkdk  ',
        'kkddddddddddddk ',
        ' kkkkkkkkkkkkk  ',
        '                ',
      ],
    },
    bld_infirmary: {
      p: { k: K, w: '#eef2f8', s: '#b6c0cf', d: '#5a6472', r: '#ff4d5e' },
      g: [
        '                ',
        '   kkkkkkkkkk   ',
        '  kwwwwwwwwwwk  ',
        ' kwwwwwrrwwwwwk ',
        ' kwwwwwrrwwwwwk ',
        ' kwwwrrrrrrwwwk ',
        ' kwwwrrrrrrwwwk ',
        'kkwwwwwrrwwwwwkk',
        'kwwwwwwrrwwwwwwk',
        'kwsswwwwwwwwsswk',
        'kwsswwkkkkwwsswk',
        'kwsswwkddkwwsswk',
        'kwwwwwkddkwwwwwk',
        'kdddddkddkdddddk',
        ' kkkkkkkkkkkkkk ',
        '                ',
      ],
    },
    bld_tower: {
      p: { k: K, w: '#b9744a', W: '#e0a06a', d: '#5c3418', s: '#8d9cb0', y: '#ffe45c' },
      g: [
        '     kkkkkk     ',
        '    kWWWWWWk    ',
        '   kWWWWWWWWk   ',
        '   kWkyykkWWk   ',
        '   kWkyykkWWk   ',
        '   kWWWWWWWWk   ',
        '   kkkkkkkkkk   ',
        '    kwkkkkwk    ',
        '    kwkddkwk    ',
        '   kwwkddkwwk   ',
        '   kwkkddkkwk   ',
        '  kwwkkddkkwwk  ',
        '  kwkkkddkkkwk  ',
        ' kwwkkkddkkkwwk ',
        ' kddkkkddkkkddk ',
        '  kkkkkkkkkkkk  ',
      ],
    },
    bld_storage: {
      p: { k: K, s: '#98a4b5', S: '#cdd8e6', d: '#4d5765', o: '#ff8a3d' },
      g: [
        '                ',
        '  kkkkkkkkkkkk  ',
        ' kSSSSSSSSSSSSk ',
        ' kSkSkSkSkSkSSk ',
        'kkkkkkkkkkkkkkkk',
        'kssssssssssssssk',
        'kskskskskskskssk',
        'kssssssssssssssk',
        'kskskskskskskssk',
        'kssoosssssoossdk',
        'kssoosssssoossdk',
        'ksssssssssssssdk',
        'kddddddddddddddk',
        ' kkkkkkkkkkkkkk ',
        '                ',
        '                ',
      ],
    },
    bld_garage: {
      p: { k: K, s: '#8d9cb0', S: '#cdd8e6', d: '#4d5765', r: '#ff4d4d', y: '#ffd23a' },
      g: [
        '                ',
        '  kkkkkkkkkkkk  ',
        ' kSSSSSSSSSSSSk ',
        ' kSyySyySyySySk ',
        'kkkkkkkkkkkkkkkk',
        'kssssssssssssssk',
        'ksskkkkkkkkkkssk',
        'ksskrrrrrrrrkssk',
        'ksskrssssssrkssk',
        'ksskrssssssrkssk',
        'ksskrrrrrrrrkssk',
        'ksskddddddddkssk',
        'ksskddddddddkssk',
        'kddkddddddddkddk',
        ' kkkkkkkkkkkkkk ',
        '                ',
      ],
    },
    bld_fire: {
      p: { k: K, y: '#ffe45c', o: '#ff9c1e', r: '#ef4423', b: '#6b4a22', d: '#3a2410' },
      g: [
        '                ',
        '       kk       ',
        '      krrk      ',
        '     krorrk     ',
        '    krooorrk    ',
        '   krooyyoork   ',
        '   krooyyyoork  ',
        '   kroyywyyork  ',
        '   kkroyywyokk  ',
        '  kbkkroooorkkbk',
        '  kbbkkkookkkbbk',
        ' kbbbbbkkkbbbbbk',
        ' kdbbbbbbbbbbbdk',
        '  kddbbbbbbbddk ',
        '   kkddddddkkk  ',
        '     kkkkkk     ',
      ],
    },
    bld_garden: {
      p: { k: K, g: '#8dff3a', d: '#2f7a1c', b: '#6b4a22', r: '#ff6b8a', y: '#ffe45c' },
      g: [
        '                ',
        '   kgk    kgk   ',
        '  kgggk  kgggk  ',
        '  kgrgkkkkgygk  ',
        '  kgggkggkgggk  ',
        '   kdk kgk kdk  ',
        '   kdkkgggkkdk  ',
        ' kgkdkkgdgkkdkgk',
        'kgggkdkkgkkdkggg',
        'kgrgkdkkdkkdkgyg',
        'kgggkdkkdkkdkggg',
        ' kdkkdkkdkkdkkdk',
        'kbbbbbbbbbbbbbbk',
        'kdbbdbbbdbbbdbbk',
        'kddddddddddddddk',
        ' kkkkkkkkkkkkkk ',
      ],
    },
    bld_statue: {
      p: { k: K, s: '#cdd8e6', S: '#98a4b5', d: '#4d5765', y: '#ffd23a' },
      g: [
        '      kkkk      ',
        '     ksssk      ',
        '     ksssk      ',
        '     kkskk      ',
        '   kkksskkk     ',
        '  kssksskssk    ',
        '  ksskssskssk   ',
        '  kSkkssskkSk   ',
        '   k kssskk     ',
        '     ksssk      ',
        '     kSSSk      ',
        '    kkSSSkk     ',
        '   kSSSSSSSk    ',
        '  kdyyyyyyydk   ',
        ' kddddddddddk   ',
        '  kkkkkkkkkk    ',
      ],
    },

    /* --------------------------------------------------- extra weapons */
    laser: {
      p: { k: K, c: '#63d3ff', C: '#d8f6ff', r: '#ff4d5e', d: '#1b6f9c', s: '#8d9cb0' },
      g: [
        '                ',
        '            kkk ',
        '        kkkkCCk ',
        '     kkkssssCCk ',
        '   kksssssssCCk ',
        '  kssdddddddsCk ',
        ' kssdCCCCCCCdsk ',
        'kcssdCCCCCCCdsk ',
        'CCCCCCCCCCCCCsk ',
        'kcssdCCCCCCCdsk ',
        ' kssdCCCCCCCdsk ',
        '  kssdddddddsCk ',
        '   kksssssssCCk ',
        '    kkrrkkkkkkk ',
        '     kkrrk      ',
        '      kkk       ',
      ],
    },
    railgun: {
      p: { k: K, s: '#9aa7b8', S: '#dbe4f0', d: '#4a5462', v: '#c68bff', V: '#efd9ff' },
      g: [
        '                ',
        '             kk ',
        '     kkkkkkkkVk ',
        '   kkSSSSSSSSVk ',
        '  kSSdddddddSVk ',
        ' kSSdvvvvvvvdVk ',
        'kkSdvVVVVVVVvdk ',
        'kSSdvVVVVVVVvdk ',
        'kSSdvVVVVVVVvdk ',
        'kkSdvvvvvvvvdkk ',
        ' kSSdddddddddk  ',
        '  kSSSSSSSSSk   ',
        '   kkdkkkkdkk   ',
        '    kdk  kdk    ',
        '   kddk  kddk   ',
        '   kkk    kkk   ',
      ],
    },
    drone: {
      p: { k: K, s: '#9aa7b8', S: '#dbe4f0', b: '#63d3ff', d: '#4a5462', r: '#ff4d5e' },
      g: [
        ' kkkk      kkkk ',
        'kbbbbk    kbbbbk',
        ' kkkk      kkkk ',
        '   kdk    kdk   ',
        '   kdkkkkkkdk   ',
        '   kdSSSSSSdk   ',
        '  kkSSSSSSSSkk  ',
        ' kSSSbbbbbbSSSk ',
        ' kSSbrrrrrrbSSk ',
        ' kSSbrrrrrrbSSk ',
        ' kSSSbbbbbbSSSk ',
        '  kdSSSSSSSSdk  ',
        '   kdkkkkkkdk   ',
        '   kdk    kdk   ',
        ' kkkk      kkkk ',
        'kbbbbk    kbbbbk',
      ],
    },

    /* ------------------------------------------------- raw resources */
    res_wood: {
      p: { k: K, b: '#8a5a2b', B: '#c07d3e', l: '#e0a45a', d: '#5c3a1c' },
      g: [
        '                ',
        '   kkkkkkkkkk   ',
        '  kBBBBBBBBBBk  ',
        ' kBlbbbbbbbblBk ',
        ' kBlbdddddbblBk ',
        ' kBlbdkkkdbblBk ',
        ' kBlbbbbbbbblBk ',
        '  kBBBBBBBBBBk  ',
        '   kkkkkkkkkk   ',
        '   kkkkkkkkkk   ',
        '  kBBBBBBBBBBk  ',
        ' kBlbbbbbbbblBk ',
        ' kBlbdkkkdbblBk ',
        ' kBlbbbbbbbblBk ',
        '  kBBBBBBBBBBk  ',
        '   kkkkkkkkkk   ',
      ],
    },
    res_ore: {
      p: { k: K, r: '#5b5f68', R: '#8f9dae', s: '#cdd6e2', y: '#ffd23a' },
      g: [
        '                ',
        '      kkkk      ',
        '    kkRRRRkk    ',
        '   kRRRRRRRRk   ',
        '  kRRsRRRRyRRk  ',
        ' kRRRRRRsRRRRRk ',
        ' kRRRRRRRRRRRRk ',
        ' kRrRRyRRRRsRRk ',
        ' kRrrRRRRRRRRRk ',
        ' kRrrrRRRRyRRRk ',
        '  kRrrrRRRRRRk  ',
        '  kRrrrrRRRRk   ',
        '   kkrrrrrkk    ',
        '     kkkkk      ',
        '                ',
        '                ',
      ],
    },
    res_stone: {
      p: { k: K, s: '#a49c96', S: '#c6bfb8', d: '#6e6862' },
      g: [
        '                ',
        '  kkkkkkkkkkkk  ',
        ' kSSSSSSSSSSSSk ',
        ' kSssssssssssSk ',
        ' kSssssssssssSk ',
        ' kSssdddsssdsSk ',
        ' kSssssssssssSk ',
        ' kSsdssssssssSk ',
        ' kSssssssdsssSk ',
        ' kSssssssssssSk ',
        ' kSssdsssssdsSk ',
        ' kSssssssssssSk ',
        ' kdddddddddddSk ',
        '  kkkkkkkkkkkk  ',
        '                ',
        '                ',
      ],
    },

    /* ------------------------------------------------ refined resources */
    res_planks: {
      p: { k: K, b: '#c08a48', B: '#e0a45a', d: '#8a5a2b', l: '#f0c58a' },
      g: [
        '                ',
        ' kkkkkkkkkkkkkk ',
        ' kBlBBBBBBBBlBk ',
        ' kbbbbbdbbbbbbk ',
        ' kkkkkkkkkkkkkk ',
        '                ',
        ' kkkkkkkkkkkkkk ',
        ' kBlBBBBdBBBBBk ',
        ' kbbbbbbbbbdbbk ',
        ' kkkkkkkkkkkkkk ',
        '                ',
        ' kkkkkkkkkkkkkk ',
        ' kBlBBBBBBBBBBk ',
        ' kbbbdbbbbbbbbk ',
        ' kkkkkkkkkkkkkk ',
        '                ',
      ],
    },
    res_metal: {
      p: { k: K, m: '#9fb0c6', M: '#c8d4e4', w: '#eef3fa', d: '#69788c' },
      g: [
        '                ',
        '                ',
        '                ',
        '     kkkkkkkk   ',
        '   kkMwwwwwwMkk ',
        '  kMMmmmmmmmmMk ',
        '  kdmmmmmmmmmdk ',
        '  kkdddddddddkk ',
        '                ',
        '   kkkkkkkkkk   ',
        ' kkMwwwwwwwwMkk ',
        'kMMmmmmmmmmmmMk ',
        'kdmmmmmmmmmmmdk ',
        'kkddddddddddddk ',
        '                ',
        '                ',
      ],
    },
    res_nails: {
      p: { k: K, n: '#c3cbd8', N: '#e6eaf2', d: '#7a8492' },
      g: [
        '                ',
        '  kkkk   kkkk   ',
        ' kNNNNk kNNNNk  ',
        ' kdnnNk kdnnNk  ',
        '  kdnk   kdnk   ',
        '  kdnk   kdnk   ',
        '  kdnk   kdnk   ',
        '  kdnk   kdnk   ',
        '  kdnk   kdnk   ',
        '  kdnk   kdnk   ',
        '  kdnk   kdnk   ',
        '  kdnk   kdnk   ',
        '   kk     kk    ',
        '    k     k     ',
        '                ',
        '                ',
      ],
    },
    res_bolts: {
      p: { k: K, b: '#9fb0c6', B: '#c8d4e4', d: '#69788c', w: '#eef3fa' },
      g: [
        '                ',
        '     kkkkkk     ',
        '    kBBwwBBk    ',
        '   kBBbbbbBBk   ',
        '  kBbbbbbbbbBk  ',
        '  kBbbdddbbbBk  ',
        '  kBbbdddbbbBk  ',
        '  kdbbbbbbbbdk  ',
        '   kdbbbbbbdk   ',
        '    kddddddk    ',
        '     kbbbbk     ',
        '     kbddbk     ',
        '     kbbbbk     ',
        '     kbddbk     ',
        '     kdddk      ',
        '      kkk       ',
      ],
    },
    res_concrete: {
      p: { k: K, c: '#b9b6ae', C: '#d6d3ca', d: '#7d7a72', r: '#8a4a2a' },
      g: [
        '                ',
        '   r        r   ',
        '   r        r   ',
        '  krk      krk  ',
        ' kkkkkkkkkkkkkk ',
        ' kCCCCCCCCCCCCk ',
        ' kCccccdcccccCk ',
        ' kCcccccccdccCk ',
        ' kCcdccccccccCk ',
        ' kCccccccdcccCk ',
        ' kCcccdccccccCk ',
        ' kddddddddddddk ',
        ' kkkkkkkkkkkkkk ',
        '                ',
        '                ',
        '                ',
      ],
    },

    /* ------------------------------------------------ crafted resources */
    res_parts: {
      p: { k: K, b: '#4aa8d8', B: '#7fd4ff', w: '#d8f2ff', d: '#2a6b8c' },
      g: [
        '                ',
        '    k kk k      ',
        '   kBkBBkBk     ',
        '  kkBBBBBBkk    ',
        '  kBBBwwBBBk    ',
        ' kkBBwddwBBkk   ',
        ' kBBBwddwBBBk   ',
        ' kBBBBwwBBBBk   ',
        ' kkBBBBBBBBkk   ',
        '  kBBBBBBBBk    ',
        '   kkBkkBkk     ',
        '      kk        ',
        '    kkbbkk      ',
        '    kbbbbk      ',
        '    kbbbbk      ',
        '    kkkkkk      ',
      ],
    },
    res_ammo: {
      p: { k: K, b: '#c8a13a', B: '#ffd23a', r: '#c4382c', R: '#ff9a8a', d: '#8a6a18' },
      g: [
        '                ',
        '   kkk    kkk   ',
        '  kRRRk  kRRRk  ',
        '  kRrRk  kRrRk  ',
        '  krrrk  krrrk  ',
        '  kkkkk  kkkkk  ',
        '  kBBBk  kBBBk  ',
        '  kBbBk  kBbBk  ',
        '  kBbBk  kBbBk  ',
        '  kBbBk  kBbBk  ',
        '  kBbBk  kBbBk  ',
        '  kdbdk  kdbdk  ',
        '  kkkkk  kkkkk  ',
        '                ',
        '                ',
        '                ',
      ],
    },
    res_tech: {
      p: { k: K, b: '#6a3aa8', B: '#d47bff', w: '#f0dcff' },
      g: [
        '                ',
        ' kkkkkkkkkkkkkk ',
        ' kbbbbbbbbbbbbk ',
        ' kbwwbbbbbbwwbk ',
        ' kbwBBBBBBBBwbk ',
        ' kbbBbbbbbbBbbk ',
        ' kbwBbBBBBbBwbk ',
        ' kbwBbBwwBbBwbk ',
        ' kbwBbBwwBbBwbk ',
        ' kbwBbBBBBbBwbk ',
        ' kbbBbbbbbbBbbk ',
        ' kbwBBBBBBBBwbk ',
        ' kbwwbbbbbbwwbk ',
        ' kbbbbbbbbbbbbk ',
        ' kkkkkkkkkkkkkk ',
        '                ',
      ],
    },

    /* ---------------------------------------------- production rooms */
    rm_mine: {
      p: { k: K, s: '#c3cbd8', S: '#eef3fa', w: '#8a5a2b', r: '#5b5f68', y: '#ffd23a' },
      g: [
        '                ',
        '  kkk      kkk  ',
        ' kSSSkk  kkSSSk ',
        ' kSssSkkkkSssSk ',
        '  kSssSSSSssSk  ',
        '   kkSssssSkk   ',
        '     kkwwkk     ',
        '      kwwk      ',
        '      kwwk      ',
        '   kkkkwwkkkk   ',
        '  krrrkwwkrrrk  ',
        ' krrrrrwwrrrrrk ',
        ' krryrrwwrryrrk ',
        ' krrrrrrrrrrrrk ',
        '  kkkkkkkkkkkk  ',
        '                ',
      ],
    },
    rm_lumber: {
      p: { k: K, w: '#8a5a2b', W: '#c07d3e', s: '#c3cbd8', S: '#eef3fa', g: '#3f8f2a' },
      g: [
        '        kk      ',
        '   kk  kSSk     ',
        '  kggk kSsSk    ',
        ' kggggkkSssk    ',
        ' kggggkkSsSk    ',
        '  kggk  kssk    ',
        '   kwk  kwwk    ',
        '   kwk  kwwk    ',
        '   kwk  kwwk    ',
        '  kkkkkkkwkkk   ',
        ' kWWWWWWWWWWWk  ',
        ' kWwwwwwwwwwWk  ',
        ' kWwkkwwkkwwWk  ',
        ' kWwwwwwwwwwWk  ',
        ' kWWWWWWWWWWWk  ',
        '  kkkkkkkkkkk   ',
      ],
    },
    rm_quarry: {
      p: { k: K, s: '#a49c96', S: '#c6bfb8', d: '#6e6862', m: '#c3cbd8', w: '#8a5a2b' },
      g: [
        '            kmk ',
        '           kmmk ',
        '          kmmk  ',
        '   kkkk  kwmk   ',
        '  kSSSSk kwk    ',
        '  kssssk kk     ',
        '  kkkkkk        ',
        ' kkkkkkkkkkk    ',
        ' kSSSSkSSSSk    ',
        ' ksssskssssk    ',
        ' ksddskssddk    ',
        ' kkkkkkkkkkk    ',
        'kkkkkkkkkkkkkk  ',
        'kSSSSkSSSSkSSk  ',
        'kssssksssskssk  ',
        'kkkkkkkkkkkkkk  ',
      ],
    },
    rm_salvage: {
      p: { k: K, s: '#c3cbd8', d: '#69788c', y: '#ffd23a', r: '#c4382c', b: '#4aa8d8' },
      g: [
        ' kkkkkkkkkkkkkk ',
        ' kdddddddddddddk',
        ' kdssssssssssddk',
        ' kkkkkkkkkkkkkkk',
        '     kddddk     ',
        '     kddddk     ',
        '  kkkkkkkkkkkk  ',
        ' krrkyykbbkyykk ',
        ' krrryykbbbyyrk ',
        ' kyyrrkkkkbbrrk ',
        ' kyybbrrbbrryyk ',
        ' krrbbyyrrbbyyk ',
        ' kyyrrbbyybbrrk ',
        ' kkkkkkkkkkkkkk ',
        '  kdddddddddk   ',
        '   kkkkkkkkk    ',
      ],
    },
    rm_hydro: {
      p: { k: K, g: '#3f8f2a', G: '#8dff3a', y: '#ffd23a', s: '#c3cbd8', d: '#69788c', b: '#4aa8d8' },
      g: [
        ' kkkkkkkkkkkkkk ',
        ' kyyyyyyyyyyyyk ',
        ' kkkkkkkkkkkkkk ',
        '  k y  y  y  k  ',
        '   kGk kGk kGk  ',
        '  kGGGkGGGkGGGk ',
        '  kgGgkgGgkgGgk ',
        '   kgk kgk kgk  ',
        '   kgk kgk kgk  ',
        ' kkkkkkkkkkkkkk ',
        ' kdbbbbbbbbbbdk ',
        ' kdddddddddddd k',
        ' kkkkkkkkkkkkkk ',
        '  kssk    kssk  ',
        '  kssk    kssk  ',
        '  kkkk    kkkk  ',
      ],
    },
    rm_derrick: {
      p: { k: K, s: '#69788c', S: '#c3cbd8', o: '#ff9c1e', d: '#3a2a18' },
      g: [
        '      kkkk      ',
        '     kSSSSk     ',
        '    kkSkkSkk    ',
        '   kSSkkkkSSk   ',
        '   kSk    kSk   ',
        '  kSSk    kSSk  ',
        '  kSk  kk  kSk  ',
        ' kSSk kook kSSk ',
        ' kSk  kook  kSk ',
        'kSSk  kook  kSSk',
        'kSk   kook   kSk',
        'kkkkkkkookkkkkkk',
        ' kddddkookdddddk',
        ' kdoooooooooodk ',
        ' kdoooooooooodk ',
        ' kkkkkkkkkkkkkk ',
      ],
    },

    /* ---------------------------------------------- processing rooms */
    rm_sawmill: {
      p: { k: K, s: '#dbe4f0', S: '#95a5bb', w: '#c07d3e', W: '#e0a45a', d: '#8a5a2b' },
      g: [
        '       kk       ',
        '      kSSk      ',
        '   k kSssSk k   ',
        '  kSkkSssSkkSk  ',
        '  kSSSSssSSSSk  ',
        ' kSsssssssssSk  ',
        ' kSsssssssssSk  ',
        '  kSSSSssSSSSk  ',
        '  kSkkSssSkkSk  ',
        '   k kSssSk k   ',
        '      kSSk      ',
        ' kkkkkkkkkkkkkk ',
        ' kWWWWWWWWWWWWk ',
        ' kwwwwwwwwwwwwk ',
        ' kddddddddddddk ',
        ' kkkkkkkkkkkkkk ',
      ],
    },
    rm_smelter: {
      p: { k: K, s: '#69788c', S: '#a4b0c0', o: '#ff8a1e', y: '#ffd23a', w: '#fff0c0' },
      g: [
        '    kk    kk    ',
        '    ko    ok    ',
        '   kkokkkkokk   ',
        '  kSSSSSSSSSSk  ',
        ' kSSssssssssSSk ',
        ' kSsssssssssssk ',
        ' kSskkkkkkkksSk ',
        ' kSskoooooooksk ',
        ' kSskoyyyyyoksk ',
        ' kSskoywwwyoksk ',
        ' kSskoyyyyyoksk ',
        ' kSskoooooooksk ',
        ' kSskkkkkkkksSk ',
        ' kSsssssssssssk ',
        ' kkkkkkkkkkkkkk ',
        '  kkk      kkk  ',
      ],
    },
    rm_nailery: {
      p: { k: K, n: '#c3cbd8', N: '#e6eaf2', d: '#69788c', y: '#ffd23a' },
      g: [
        ' kkkkkkkkkkkkkk ',
        ' kddddddddddddk ',
        ' kdNNNNNNNNNNdk ',
        ' kddddddddddddk ',
        '  kkkkkkkkkkkk  ',
        '     kddddk     ',
        '     kdyydk     ',
        '     kddddk     ',
        '  kkkkkkkkkkkk  ',
        ' kkNkkkNkkkNkkk ',
        ' kNNNkNNNkNNNk  ',
        ' kdnnkdnnkdnnk  ',
        '  knk  knk  knk ',
        '  knk  knk  knk ',
        '  kkk  kkk  kkk ',
        '                ',
      ],
    },
    rm_machine: {
      p: { k: K, s: '#9fb0c6', S: '#c8d4e4', d: '#69788c', y: '#ffd23a', w: '#eef3fa' },
      g: [
        '                ',
        '   kk      kk   ',
        '  kSSkkkkkkSSk  ',
        ' kSSSSSSSSSSSSk ',
        ' kSsssssssssssk ',
        ' kSskkkkkkkkssk ',
        ' kSskyyyyyykssk ',
        ' kSskywwwwykssk ',
        ' kSskywddwykssk ',
        ' kSskywwwwykssk ',
        ' kSskyyyyyykssk ',
        ' kSskkkkkkkkssk ',
        ' kSsssssssssssk ',
        ' kddddddddddddk ',
        ' kkkkkkkkkkkkkk ',
        '  kkk      kkk  ',
      ],
    },
    rm_mixer: {
      p: { k: K, c: '#b9b6ae', C: '#d6d3ca', s: '#69788c', S: '#a4b0c0', d: '#7d7a72' },
      g: [
        '                ',
        '      kkkk      ',
        '    kkSSSSkk    ',
        '   kSSCCCCSSk   ',
        '  kSCCccccCCSk  ',
        '  kSCcccdcccSk  ',
        ' kSCcccdccccCSk ',
        ' kSCccdcccdccSk ',
        ' kSCcccccccccSk ',
        '  kSCccdcccCSk  ',
        '  kSSCCccCCSSk  ',
        '   kkSSSSSSkk   ',
        '     kkSSkk     ',
        '   kkkkSSkkkk   ',
        '  kssssssssssk  ',
        '  kkkkkkkkkkkk  ',
      ],
    },
    rm_assembly: {
      p: { k: K, s: '#69788c', S: '#a4b0c0', b: '#4aa8d8', B: '#7fd4ff', y: '#ffd23a' },
      g: [
        '                ',
        '   kkk    kkk   ',
        '  kSSSk  kSSSk  ',
        '  kSsSk  kSsSk  ',
        '  kkSkk  kkSkk  ',
        '   kSk    kSk   ',
        '   kSk    kSk   ',
        '  kkkk    kkkk  ',
        '  kBBk    kBBk  ',
        ' kkkkkkkkkkkkkk ',
        ' kBBBk kBBBk yk ',
        ' kbbbk kbbbk yk ',
        ' kkkkkkkkkkkkkk ',
        ' kSssSssSssSssk ',
        ' kkkkkkkkkkkkkk ',
        '  kk kk kk kk   ',
      ],
    },

    /* ------------------------------------------------- special rooms */
    rm_quarters: {
      p: { k: K, w: '#8a5a2b', W: '#c07d3e', s: '#c3cbd8', b: '#4aa8d8', B: '#9ad6ff' },
      g: [
        ' kk          kk ',
        ' kWk        kWk ',
        ' kWkkkkkkkkkkWk ',
        ' kWBBBBBBBBBBWk ',
        ' kWbbbbbbbbbbWk ',
        ' kWkkkkkkkkkkWk ',
        ' kWk        kWk ',
        ' kWk        kWk ',
        ' kWkkkkkkkkkkWk ',
        ' kWBBBBBBBBBBWk ',
        ' kWbbbbbbbbbbWk ',
        ' kWkkkkkkkkkkWk ',
        ' kWk        kWk ',
        ' kWk        kWk ',
        ' kkk        kkk ',
        '                ',
      ],
    },
    rm_generator: {
      p: { k: K, s: '#69788c', S: '#a4b0c0', y: '#ffd23a', w: '#fff8c0', d: '#3a3f48' },
      g: [
        '     kk         ',
        '     kdk        ',
        '  kkkkdkkkkkk   ',
        ' kSSSSSSSSSSSk  ',
        ' kSsssssssssSk  ',
        ' kSskkkkkkksSk  ',
        ' kSsk    ykssk  ',
        ' kSsk   ywkssk  ',
        ' kSsk  ywwkkssk ',
        ' kSsk yww ykssk ',
        ' kSsk  yw ykssk ',
        ' kSsk   y kssk  ',
        ' kSskkkkkkksSk  ',
        ' kSsssssssssSk  ',
        ' kkkkkkkkkkkkk  ',
        '  kkk     kkk   ',
      ],
    },
    rm_garage: {
      p: { k: K, r: '#c4382c', R: '#ff6b5e', s: '#69788c', S: '#c3cbd8', d: '#2a2f38' },
      g: [
        ' kkkkkkkkkkkkkk ',
        ' kSSSSSSSSSSSSk ',
        ' kSkkkkkkkkkkSk ',
        ' kSkssssssssksk ',
        ' kSkkkkkkkkkksk ',
        ' kSkssssssssksk ',
        ' kSkkkkkkkkkksk ',
        '  kkkkkkkkkkkk  ',
        '   kkkkkkkkkk   ',
        '  kRRRRRRRRRRk  ',
        ' kRRrrrrrrrrRRk ',
        ' kRrrrrrrrrrrRk ',
        ' kkkkkkkkkkkkkk ',
        ' kdSdkkkkkkdSdk ',
        ' kdddk    kdddk ',
        '  kkk      kkk  ',
      ],
    },
    rm_lab: {
      p: { k: K, b: '#6a3aa8', B: '#d47bff', w: '#f0dcff', g: '#8dff3a' },
      g: [
        '     kkkkkk     ',
        '     kwwwwk     ',
        '     kw  wk     ',
        '     kw  wk     ',
        '     kw  wk     ',
        '    kkw  wkk    ',
        '    kw    wk    ',
        '   kkw    wkk   ',
        '   kwBBBBBBwk   ',
        '  kkwBBggBBwkk  ',
        '  kwBBgggggBwk  ',
        '  kwBgggggggwk  ',
        '  kwBBgggggBwk  ',
        '   kwBBBBBBwk   ',
        '   kkwwwwwwkk   ',
        '     kkkkkk     ',
      ],
    },
    rm_armory: {
      p: { k: K, s: '#69788c', S: '#c3cbd8', d: '#3a2a18', w: '#8a5a2b', r: '#c4382c' },
      g: [
        '                ',
        '  kkkkkkkkkkk   ',
        ' kSSSSSSSSSSSk  ',
        ' kSssssssssssk  ',
        ' kkkkkkkkkkkkk  ',
        '   kwk  kwk     ',
        '   kwk  kwk     ',
        '  kkskkkkskkk   ',
        ' kSssSkkSssSk   ',
        ' kSsSkrrkSsSk   ',
        ' kkSkkrrkkSkk   ',
        '  kSk krk kSk   ',
        '  kSk krk kSk   ',
        '  kdk kkk kdk   ',
        '  kkk     kkk   ',
        '                ',
      ],
    },
  };

  const cache = new Map();

  function render(id, scale) {
    const key = id + '@' + scale;
    if (cache.has(key)) return cache.get(key);
    const def = ICONS[id];
    if (!def) return '';

    const src = document.createElement('canvas');
    src.width = src.height = SIZE;
    const sctx = src.getContext('2d');
    const img = sctx.createImageData(SIZE, SIZE);

    for (let y = 0; y < SIZE; y++) {
      const row = def.g[y] || '';
      for (let x = 0; x < SIZE; x++) {
        const ch = row[x] || ' ';
        const hex = def.p[ch];
        const o = (y * SIZE + x) * 4;
        if (!hex) { img.data[o + 3] = 0; continue; }
        img.data[o] = parseInt(hex.slice(1, 3), 16);
        img.data[o + 1] = parseInt(hex.slice(3, 5), 16);
        img.data[o + 2] = parseInt(hex.slice(5, 7), 16);
        img.data[o + 3] = 255;
      }
    }
    sctx.putImageData(img, 0, 0);

    const out = document.createElement('canvas');
    out.width = out.height = SIZE * scale;
    const octx = out.getContext('2d');
    octx.imageSmoothingEnabled = false;
    octx.drawImage(src, 0, 0, out.width, out.height);
    const url = out.toDataURL('image/png');
    cache.set(key, url);
    return url;
  }

  BA.icons = {
    url: (id, scale) => render(id, scale || 4),
    img: (id, px, cls) => {
      const url = render(id, 4);
      if (!url) return '';
      return `<img class="pxi${cls ? ' ' + cls : ''}" src="${url}" width="${px}" height="${px}" alt="">`;
    },
    has: (id) => !!ICONS[id],
    ids: () => Object.keys(ICONS),
  };
})();
